# configs/train.yaml

project:
  name: resnet-fruits

data:
  root: "../../data/fruits-360"
  image_size: 100
  batch_size: 128
  augment: true

model:
  backbone: resnet50
  freeze_backbone: true
  num_classes: 60

training:
  epochs: 16
  learning_rate: 0.001
  checkpoint_dir: "../outputs/checkpoints"